config/routes.rb
Rails.application.routes.draw do
  resources :cats
  devise_for :users
  
  root 'cats#cat_mark'
  post 'add_sweetness/:id' => 'cats#add_sweetness'
  
  get 'top_today' => 'cats#top_today'
  get 'top_last_week' => 'cats#top_last_week'
  get 'top_last_month' => 'cats#top_last_month'
  get 'top_ever' => 'cats#top_ever'

end

app/models/cat.rb
class Cat < ActiveRecord::Base
  
  require 'flickraw'
  
  has_many :sweetness
  
  FlickRaw.api_key="24136702cabc673f44ff21d2cbc5b84d"
  FlickRaw.shared_secret="95fc072301938e0c"
  
  mount_uploader :picture, CatUploader
  
  paginates_per 20
  
  class << self
  
    def find_new_cat
      source = flickr.photos.search(:text => 'cat', :page => 1, :per_page => 100)
      cursor = 1
      picture_number = 0
    
      cat = nil
    
      while cat.nil? do
      
        if cursor % 100 == 0
          source = flickr.photos.search(:text => 'cat', :page => cursor % 100, :per_page => 100)
          picture_number = 0
        end
      
        if Cat.find_by_flickr_id(source[picture_number].id).nil?
          cat = source[picture_number]
        end
      
        picture_number += 1
        cursor += 1
      end
      cat
    end
  
    def save_new
      new_cat = self.find_new_cat
      if new_cat
        begin
          info = flickr.photos.getInfo(:photo_id => new_cat.id)
          source = FlickRaw.url_q(info)
          c = Cat.create!(name: new_cat.title, flickr_id: new_cat.id)
          c.remote_picture_url = source
          c.save!
        rescue => error
          puts error
        end
      end
    end
    
    def save_new_100
      100.times do
        save_new
      end
    end
  
    def random n
      if count > n
        ids = Cat.all.map( &:id )
        arr = Cat.find( (1..n).map { ids.delete_at( ids.size * rand ) } )
        if arr.count == 1
          arr.first
        else
          arr
        end
      else
        nil
      end
    end
    
    def top_ten
      all_ordered.first(10)
    end
    
    def top_ten_in n
      all.sort_by {|cat| cat.sweets_in n}.reverse.first(10)
    end
  
    def top n
      all.sort_by(&:sweets).reverse.limit(n)
    end
    
    def all_ordered
      all.sort_by(&:sweets).reverse
    end
    
  end # end of self
  
  def sweets
    sweetness.count
  end
  
  def sweets_in n
    sweetness.where("created_at > ?", Date.today - n.days).count
  end
  
end

app/models/sweetness.rb
class Sweetness < ActiveRecord::Base
  
  belongs_to :cat
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  
  before_filter :authenticate_user!
  before_filter :check_admin, only: [:index]
  
  def cat_mark
    @cat = Cat.random 2
  end
  
  def add_sweetness
    @cat = Cat.find(params[:id])
    
    respond_to do |format|
      format.js{
        @cat.sweetness.create!(value: 1)
        render :text => "success"
      }
    end
  end
  
  def index
    @cats = Kaminari.paginate_array(Cat.all_ordered).page(params[:page])
  end
  
  def top_today
    @cats = Cat.top_ten_in 1
    render 'top_ten'
  end
  
  def top_last_week
    @cats = Cat.top_ten_in 7  
    render 'top_ten'
  end
  
  def top_last_month
    @cats = Cat.top_ten_in 30
    render 'top_ten'
  end
  
  def top_ever
    @cats = Cat.top_ten
    render 'top_ten'
  end
  
  private
  
    def check_admin
      if !current_user.admin then redirect_to root_path end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cats/_cat.html.erb
  <div class="col-md-3 col-md-offset-1 cat">
    <%= image_tag cat.picture.url, width: '100%', height: 'auto' %>
  </div>

app/views/cats/_cats.html.erb
<% @cats.each_with_index do |cat, index| %>
  <div class="row">
    <div class="col-md-3">
      <%= image_tag cat.picture.url, width: '100%', height: 'auto' %>
    </div>

    <div class="col-md-8">
      <h3><%= cat.name%></h3><br />
      sweetness: <%= cat.sweets%>
    </div>
  </div>
  <br />
<% end %>

app/views/cats/cat_mark.html.erb
<div class="container jumbotron">
  <div class="row">
    <div class="col-md-12 text-center">
      <h1>Which one do you prefer?</h1>
    </div>
    <div class="col-md-1"></div>
    <% if @cat%>
      <% @cat.each_with_index do |cat, index|%>
        <div class="col-md-5 cat_mark <% if index % 2 == 1 then %>col-md-offset-1 <% end %>" data-cat-id="<%= cat.id%>">
          <%= image_tag cat.picture.url, width: '80%', height: 'auto' %>
        </div>
      <% end %>
    <% else %>
      There are no cats yet!
    <% end %>
  </div>
</div>

app/views/cats/index.html.erb
<h2 class="text-center">Cats index</h2>
<div class="container jumbotron infinite-table">
  <table>
    <%= render :partial => 'cats', :object => @cats %>
  </table>
  <p class="pagination">
    <%= link_to_next_page(@cats, 'Next Page', :remote => true) %>
    pagination
  </p>
</div>

app/views/cats/index.js.erb
$("<%=j render(:partial => 'cats', :object => @cats) %>")
  .appendTo($(".infinite-table table"));

// Update pagination link
<% if @cats.last_page? %>
  $('.pagination').html("That's all, folks!");
<% else %>
  $('.pagination')
    .html("<%=j link_to_next_page(@cats, 'Next Page', :remote => true) %>");
<% end %>

app/views/cats/top_ten.html.erb
<div class="container jumbotron">
  <% @cats.each do |cat| %>
    <%= render cat %>
  <% end %>
</div>

app/views/layouts/_header.html.erb
<nav class="row navbar navbar-default">
  <% if user_signed_in? && current_user.admin %>
    <%= link_to "Catzone", cats_path, class: "navbar-brand col-md-2 text-center" %>
  <% else %>
    <%= link_to "Catzone", root_path, class: "navbar-brand col-md-2 text-center" %>
  <% end %>
  <div class="col-md-2">
    <%= link_to "top 10 today", top_today_path, class: "btn btn-large"%>
  </div>
  <div class="col-md-2">
    <%= link_to "top 10 this week", top_last_week_path, class: "btn btn-large"%>
  </div>
  <div class="col-md-2">
    <%= link_to "top 10 this month", top_last_month_path, class: "btn btn-large"%>
  </div>
  <div class="col-md-2">
    <%= link_to "top 10 ever!", top_ever_path, class: "btn btn-large"%>
  </div>
  <div class="col-md-2">
    <%= link_to "log out", destroy_user_session_path, method: 'delete', class: "btn btn-large"%>    
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Catzone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/header" %>
  <%= yield %>

</body>
</html>